project:
  type: website
  output-dir: docs

website:
  title: "Website"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - nascar.qmd
      - plots.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

