project:
  type: website
  output-dir: docs

website:
  title: "Website"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - nascar.qmd
      - plots.qmd

format:
  html:
    theme: darkly
    backgroundcolor: "#333333"
    fontcolor: "white"
    linkcolor: "#FFD700"
    monobackgroundcolor: "#000000"
    css: styles.css

editor: visual

